site_name: Documentacion de Justflix
theme:
  name: material
nav:
  - Inicio: index.md
  - Justflix_ENV: env.md
  - Catalogo: catalogo.md
  - Suscripciones: suscripciones.md
  - Multimedia: multimedia.md
  - Reproductor: reproductor.md
  - Admin: admin_front.md
  - Videos: videos_sostenibilidad.md
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/